### ISSUE TITLE
Error while building project 

### ISSUE THREAD

**Issue by ChaitanyaPTank** [tk-shirasaka/envim#12]
Hi, I just tried to build the project with `make windows` but it fails with below error. Also getting the same error on Ubuntu 20.04
```
npm install

up to date, audited 465 packages in 1s

55 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (2 moderate, 1 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
curl -L  -o .zip
curl: (2) no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
mingw32-make: *** [Makefile:22: fonts/NORMAL/.zip] Error 2
```

**Comment by tksrsk** [comment]
Sorry for not maintaining the README.md.
If you build this application, you will need to modify the Makefile to download the fonts.

Could you try to build it after changing the Makefile with the following example?

eg.
```
NORMAL_FONT_DOWNLOAD_URL = https://github.com/yuru7/PlemolJP/releases/download/v1.6.0/PlemolJP_NF_v1.6.0.zip
NORMAL_FONT_DOWNLOAD_FILE = PlemolJP_NF_v1.6.0
NORMAL_REGULAR_FONT_FILE_NAME = PlemolJP_NF_v1.6.0/PlemolJPConsole_NF/PlemolJPConsoleNF-Regular.ttf
NORMAL_BOLD_FONT_FILE_NAME = PlemolJP_NF_v1.6.0/PlemolJPConsole_NF/PlemolJPConsoleNF-Bold.ttf
```

**Comment by ChaitanyaPTank** [comment]
Yes I was able to build the project, but It was stuck to the setting page, and did not get to the editor it self.
Here is what I am getting when I press start.
```
DevTools listening on ws://127.0.0.1:8315/devtools/browser/76721879-efdc-4dda-b19e-101235586063
Error occurred in handler for 'envim:setting': TypeError: Cannot read properties of undefined (reading 'presets')
    at e.set (D:\Chaitanya\experiments\envim\dist\win-unpacked\resources\app.asar\main.js:2:556517)
    at onSetting (D:\Chaitanya\experiments\envim\dist\win-unpacked\resources\app.asar\main.js:2:532597)
    at D:\Chaitanya\experiments\envim\dist\win-unpacked\resources\app.asar\main.js:2:528819
    at Array.map (<anonymous>)
    at Function.<anonymous> (D:\Chaitanya\experiments\envim\dist\win-unpacked\resources\app.asar\main.js:2:528793)
    at D:\Chaitanya\experiments\envim\dist\win-unpacked\resources\app.asar\main.js:2:527806
    at Object.next (D:\Chaitanya\experiments\envim\dist\win-unpacked\resources\app.asar\main.js:2:527911)
    at D:\Chaitanya\experiments\envim\dist\win-unpacked\resources\app.asar\main.js:2:526802
    at new Promise (<anonymous>)
    at r (D:\Chaitanya\experiments\envim\dist\win-unpacked\resources\app.asar\main.js:2:526547)
```

**Comment by tksrsk** [comment]
@ChaitanyaPTank 
Thanks for letting me know.
I have fixed it, can you please get the latest source and rebuild it?

**Comment by ChaitanyaPTank** [comment]
Thanks @tk-shirasaka I took pull from master and it's working.
I am not sure how much time I will be able to contribute to this, but wanna give it a shot. Can you please help me with `good first issue` or something like that? or from where should I start to understand the codebase ?

**Comment by tksrsk** [comment]
Thank you for your offer!

I don't have the documentation ready, but the general structure uses `Electron` for the backend and `React` for the frontend, and each has its own directory, so you can start reading from where you are interested.

> . /main -- backend (Electron)
> . /renderer -- frontend (React)

To understand the backend, it is necessary to understand Neovim's UI API, so please refer to the official documentation to deepen your understanding.

Please refer to the official documentation at https://neovim.io/doc/user/ui.html

You can also check the communication between the frontend and backend by clicking the debug icon in the lower right corner of the screen and entering a regular expression string to filter the communication.
When passing data from the backend to the frontend, the data received by the Neovim API is processed, so most of the parts do not match the documentation, but please refer to it for reference only.
(If you don't want to filter the data, use `.*` to see all the communication without filtering).

If you want to finish checking the communication, click the same icon again and type in an empty string.

Also, if you set the `DEVELOPMENT` environment variable during the build process, typescript compression will not be performed, which may help you identify the error location.
Even if you do not set the environment variable, you can substitute it by changing the relevant part of the Makefile as follows and building.

- Before
```bash
npm run build
```

- After
```bash
DEVELOPMENT=1 npm run build
```

Thank you for your cooperation.

**Comment by ChaitanyaPTank** [comment]
Thanks for the reply @tk-shirasaka.

Does this project have HMR? I am just trying to do changes here and there in the code but every time I need to restart the servers to get the results.

It'll we good if we can connect on discord or something similar.

Thanks

**Comment by tksrsk** [comment]
@ChaitanyaPTank 
Sorry for the late reply.

Unfortunately this project is not on HMR.
My development environment resides on a docker container and I build it every time I check it works.

I used to be able to run `npm run start` and `npm run watch` to check after reloading, but I just checked and it seems to have stopped working.

I will try to adjust it as soon as I see it, so may I have some time?
